=== nayot/seagames/MicroFlap/Datum.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Jacinto Verdaguer (DSSA) -->
<!--DTD generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<!ELEMENT Datum (Ellipsoid, Delta, Error, Region)>
<!ATTLIST Datum
	Name CDATA #REQUIRED
>
<!ELEMENT DatumFile (Ellipsoids, Datums)>
<!ELEMENT Datums (Datum+)>
<!ELEMENT Delta (#PCDATA)>
<!ELEMENT Ellipsoid (#PCDATA)>
<!ATTLIST Ellipsoid
	Name CDATA #IMPLIED
>
<!ELEMENT Ellipsoids (Ellipsoid+)>
<!ELEMENT Error (#PCDATA)>
<!ELEMENT Region (#PCDATA)>

=== nayot/seagames/MicroFlap/Datums.xml
<?xml version="1.0" encoding="ISO8859-1"?>
<!DOCTYPE DatumFile SYSTEM "Datum.dtd">
<DatumFile>
	<Datums>
		<!-- Datum: Name, Ellipsoid (one from above), Delta with respect to WGS84 (x, y, z), Cartographic Error (x, y, z), Region of Use -->
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-118 -14 218</Delta>
			<Error>25 25 25</Error>
			<Region>Burkina Faso</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-134 -2 210</Delta>
			<Error>25 25 25</Error>
			<Region>Cameroon</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-165 -11 206</Delta>
			<Error>3 3 3</Error>
			<Region>Ethiopia</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-123 -20 220</Delta>
			<Error>25 25 25</Error>
			<Region>Mali</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-166 -15 204</Delta>
			<Error>5 5 3</Error>
			<Region>MEAN FOR Ethiopia; Sudan</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-128 -18 224</Delta>
			<Error>25 25 25</Error>
			<Region>Senegal</Region>
		</Datum>
		<Datum Name="Adindan">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-161 -14 205</Delta>
			<Error>3 5 3</Error>
			<Region>Sudan</Region>
		</Datum>
		<Datum Name="Afgooye">
			<Ellipsoid>Krassovsky 1940</Ellipsoid>
			<Delta>-43 -163 45</Delta>
			<Error>25 25 25</Error>
			<Region>Somalia</Region>
		</Datum>
		<Datum Name="Ain el Abd 1970">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-150 -250 -1</Delta>
			<Error>25 25 25</Error>
			<Region>Bahrain</Region>
		</Datum>
		<Datum Name="Ain el Abd 1970">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-143 -236 7</Delta>
			<Error>10 10 10</Error>
			<Region>Saudi Arabia</Region>
		</Datum>
		<Datum Name="American Samoa 1962">
			<Ellipsoid>Clarke 1866</Ellipsoid>
			<Delta>-115 118 426</Delta>
			<Error>25 25 25</Error>
			<Region>American Samoa Islands</Region>
		</Datum>
		<Datum Name="Anna 1 Astro 1965">
			<Ellipsoid>Australian National</Ellipsoid>
			<Delta>-491 -22 435</Delta>
			<Error>25 25 25</Error>
			<Region>Cocos Islands</Region>
		</Datum>
		<Datum Name="Antigua Island Astro 1943">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-270 13 62</Delta>
			<Error>25 25 25</Error>
			<Region>Antigua (Leeward Islands)</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-138 -105 -289</Delta>
			<Error>3 5 3</Error>
			<Region>Botswana</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-153 -5 -292</Delta>
			<Error>20 20 20</Error>
			<Region>Burundi</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-125 -108 -295</Delta>
			<Error>3 3 8</Error>
			<Region>Lesotho</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-161 -73 -317</Delta>
			<Error>9 24 8</Error>
			<Region>Malawi</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-143 -90 -294</Delta>
			<Error>20 33 20</Error>
			<Region>MEAN FOR Botswana; Lesotho; Malawi; Swaziland; Zaire; Zambia; Zimbabwe</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-134 -105 -295</Delta>
			<Error>15 15 15</Error>
			<Region>Swaziland</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-169 -19 -278</Delta>
			<Error>25 25 25</Error>
			<Region>Zaire</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-147 -74 -283</Delta>
			<Error>21 21 27</Error>
			<Region>Zambia</Region>
		</Datum>
		<Datum Name="Arc 1950">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-142 -96 -293</Delta>
			<Error>5 8 11</Error>
			<Region>Zimbabwe</Region>
		</Datum>
		<Datum Name="Arc 1960">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-160 -6 -302</Delta>
			<Error>20 20 20</Error>
			<Region>MEAN FOR Kenya; Tanzania</Region>
		</Datum>
		<Datum Name="Arc 1960">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-157 -2 -299</Delta>
			<Error>4 3 3</Error>
			<Region>Kenya</Region>
		</Datum>
		<Datum Name="Arc 1960">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-175 -23 -303</Delta>
			<Error>6 9 10</Error>
			<Region>Taanzania</Region>
		</Datum>
		<Datum Name="Ascension Island 1958">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-205 107 53</Delta>
			<Error>25 25 25</Error>
			<Region>Ascension Island</Region>
		</Datum>
		<Datum Name="Astro Beacon E 1945">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>145 75 -272</Delta>
			<Error>25 25 25</Error>
			<Region>Iwo Jima</Region>
		</Datum>
		<Datum Name="Astro DOS 71/4">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-320 550 -494</Delta>
			<Error>25 25 25</Error>
			<Region>St Helena Island</Region>
		</Datum>
		<Datum Name="Astro Tern Island (FRIG) 1961">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>114 -116 -333</Delta>
			<Error>25 25 25</Error>
			<Region>Tern Island</Region>
		</Datum>
		<Datum Name="Astronomical Station 1952">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>124 -234 -25</Delta>
			<Error>25 25 25</Error>
			<Region>Marcus Island</Region>
		</Datum>
		<Datum Name="Australian Geodetic 1966">
			<Ellipsoid>Australian National</Ellipsoid>
			<Delta>-133 -48 148</Delta>
			<Error>3 3 3</Error>
			<Region>Australia; Tasmania</Region>
		</Datum>
		<Datum Name="Australian Geodetic 1984">
			<Ellipsoid>Australian National</Ellipsoid>
			<Delta>-134 -48 149</Delta>
			<Error>2 2 2</Error>
			<Region>Australia; Tasmania</Region>
		</Datum>
		<Datum Name="Ayabelle Lighthouse">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-79 -129 145</Delta>
			<Error>25 25 25</Error>
			<Region>Djibouti</Region>
		</Datum>
		<Datum Name="Bellevue (IGN)">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-127 -769 472</Delta>
			<Error>20 20 20</Error>
			<Region>Efate and Erromango Islands</Region>
		</Datum>
		<Datum Name="Bermuda 1957">
			<Ellipsoid>Clarke 1866</Ellipsoid>
			<Delta>-73 213 296</Delta>
			<Error>20 20 20</Error>
			<Region>Bermuda</Region>
		</Datum>
		<Datum Name="Bissau">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-173 253 27</Delta>
			<Error>25 25 25</Error>
			<Region>Guinea-Bissau</Region>
		</Datum>
		<Datum Name="Bogota Observatory">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>307 304 -318</Delta>
			<Error>6 5 6</Error>
			<Region>Colombia</Region>
		</Datum>
		<Datum Name="Bukit Rimpah">
			<Ellipsoid>Bessel 1841</Ellipsoid>
			<Delta>-384 664 -48</Delta>
			<Error>-1 -1 -1</Error>
			<Region>Indonesia (Bangka and Belitung Ids)</Region>
		</Datum>
		<Datum Name="Camp Area Astro">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-104 -129 239</Delta>
			<Error>-1 -1 -1</Error>
			<Region>Antarctica (McMurdo Camp Area)</Region>
		</Datum>
		<Datum Name="Campo Inchauspe">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-148 136 90</Delta>
			<Error>5 5 5</Error>
			<Region>Argentina</Region>
		</Datum>
		<Datum Name="Canton Astro 1966">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>298 -304 -375</Delta>
			<Error>15 15 15</Error>
			<Region>Phoenix Islands</Region>
		</Datum>
		<Datum Name="Cape">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-136 -108 -292</Delta>
			<Error>3 6 6</Error>
			<Region>South Africa</Region>
		</Datum>
		<Datum Name="Cape Canaveral">
			<Ellipsoid>Clarke 1866</Ellipsoid>
			<Delta>-2 151 181</Delta>
			<Error>3 3 3</Error>
			<Region>Bahamas; Florida</Region>
		</Datum>
		<Datum Name="Carthage">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-263 6 431</Delta>
			<Error>6 9 8</Error>
			<Region>Tunisia</Region>
		</Datum>
		<Datum Name="Chatham Island Astro 1971">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>175 -38 113</Delta>
			<Error>15 15 15</Error>
			<Region>New Zealand (Chatham Island)</Region>
		</Datum>
		<Datum Name="Chua Astro">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-134 229 -29</Delta>
			<Error>6 9 5</Error>
			<Region>Paraguay</Region>
		</Datum>
		<Datum Name="Corrego Alegre">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-206 172 -6</Delta>
			<Error>5 3 5</Error>
			<Region>Brazil</Region>
		</Datum>
		<Datum Name="Dabola">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>-83 37 124</Delta>
			<Error>15 15 15</Error>
			<Region>Guinea</Region>
		</Datum>
		<Datum Name="Deception Island">
			<Ellipsoid>Clarke 1880</Ellipsoid>
			<Delta>260 12 -147</Delta>
			<Error>20 20 20</Error>
			<Region>Deception Island; Antarctia</Region>
		</Datum>
		<Datum Name="Djakarta (Batavia)">
			<Ellipsoid>Bessel 1841</Ellipsoid>
			<Delta>-377 681 -50</Delta>
			<Error>3 3 3</Error>
			<Region>Indonesia (Sumatra)</Region>
		</Datum>
		<Datum Name="DOS 1968">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>230 -199 -752</Delta>
			<Error>25 25 25</Error>
			<Region>New Georgia Islands (Gizo Island)</Region>
		</Datum>
		<Datum Name="Easter Island 1967">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>211 147 111</Delta>
			<Error>25 25 25</Error>
			<Region>Easter Island</Region>
		</Datum>
		<Datum Name="Estonia; Coordinate System 1937">
			<Ellipsoid>Bessel 1841</Ellipsoid>
			<Delta>374 150 588</Delta>
			<Error>2 3 3</Error>
			<Region>Estonia</Region>
		</Datum>
		<Datum Name="European 1950">
			<Ellipsoid>International 1924</Ellipsoid>
			<Delta>-104 -101 -140</Delta>
			<Error>15 15 15</Error>
